version: '2.1'

services:
  eureka-server:
    build: eureka-server/
    restart: always
    network_mode: "host"
    hostname: localhost
    image: eureka-server
    ports:
      - 8761:8761

  config-service:
    build: config-server/
    restart: always
    network_mode: "host"
    image: config-service
    hostname: localhost
    ports:
      - 8888:8888

  zuul-api:
    build: zuul-api/
    depends_on:
      - config-service
      - eureka-server
    restart: always
    network_mode: "host"
    image: zuul-api
    hostname: localhost
    ports:
      - 8080:8080
  mongo:
   image: mongo:3.4-jessie
   ports:
     - 27017:27017
   expose:
     - 27017
   container_name: mongo
   network_mode: host
   hostname: localhost
   restart: always

  survey-service:
   build: survey-service/
   container_name: survey-service
   depends_on:
     - mongo
   network_mode: "host"
   image: survey-service
   hostname: localhost
   ports:
     - 8090:8090
